config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end
  
  root 'articles#index'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
    validates :title, presence: true
    validates :content, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def index
        @articles = Article.all
    end
    
    def show
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to articles_path
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @article.update(article_params)
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @article.destroy
        redirect_to articles_path
    end
    
    
    private
    
        def article_params
            params[:article].permit(:title, :content)
        end
        
        def set_article
            @article = Article.find(params[:id])
        end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    before_action :set_article, only: [:new, :create, :edit, :update, :destroy]
    before_action :set_comment, only: [:edit, :update, :destroy]
    
    
    def new
        @comment = Comment.new(article_id: :article_id)
    end
    
    def create 
        @comment = @article.comments.new(comment_params)
        if @comment.save
            redirect_to article_path(@article.id)
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @comment.update(comment_params)
            redirect_to article_path(@article.id)
        else
            render 'edit'
        end
    end
    
    def destroy
        @comment.destroy
        redirect_to article_path(@article.id)
    end
    
    
    private
    
        def comment_params
            params[:comment].permit(:content)
        end
        
        def set_article
            @article = Article.find(params[:article_id])
        end
        
        def set_comment
            @comment = Comment.find(params[:id])
        end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

<p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %> <br>
    <%= f.label :content %> <br>
    <%= f.text_area :content %><br>
    
    <% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    <% end %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h2>記事の内容の変更</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<ul>
    <% @articles.each do |article| %>
    <li>
        <%= link_to article.title, article_path(article.id) %>
        <%= link_to "[記事の編集]", edit_article_path(article.id) %>
        <%= link_to "[記事の削除]", article_path(article.id), method: :delete, data: { confirm: "are you sure?" } %>
    </li>
    <% end %>
</ul>

<%= link_to "新しい記事の作成", new_article_path %>

app/views/articles/new.html.erb
<h2>新しい記事の作成</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>

<p>
    <%= @article.content %>
</p>

<p>
    <%= link_to "[コメントの追加]", new_article_comment_path(@article.id) %>
</p>

<h3>
    コメント一覧
</h3>

<ul>
    <% @article.comments.each do |comment| %>
    <li>
        <%= comment.content %>
        <%= link_to "[コメントの編集]", edit_article_comment_path(id: comment.id, article_id: @article.id) %>
        <%= link_to "[コメントの削除]", article_comment_path(comment.id, article_id: @article.id), method: :delete, data: { confirm: "are you sure?" } %>
    </li>
    <% end %>
</ul>

<p>
    <%= link_to "[記事の編集]", edit_article_path(@article.id) %>
    <%= link_to "[記事の削除]", article_path(@article.id), method: :delete, data: { confirm: "are you sure?" } %>
</p>

app/views/comments/edit.html.erb
<h2><%= @article.title %></h2>

<h3>コメントの編集</h3>

<%= form_for @comment, url: {action: :update} do |f| %>

<p>
    <%= f.label :content %> <br>
    <%= f.text_area :content %><br>
    
    <% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    <% end %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/comments/new.html.erb
<h2><%= @article.title %></h2>

<h3>新しいコメントの作成</h3>

<%= form_for @comment, url: {action: :create} do |f| %>

<p>
    <%= f.label :content %> <br>
    <%= f.text_area :content %><br>
    
    <% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    <% end %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>ゆっこのブログ</h1>

  <%= yield %>

</body>

<p>
  <%= link_to "HOME", articles_path %>
</p>
</html>